version: '3.1'

services:
  dagcraft-api:
    container_name: dagcraft-api
    build: .
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8095
    volumes:
      - .:/usr/src
    ports:
      - 8095:8095
    env_file:
      - .env
    network_mode: host
