version: '3.1'

services:
  dagcraft-api:
    container_name: dagcraft-api
    build: .
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8095
    volumes:
      - .:/usr/src
    ports:
      - 8095:8095
    env_file:
      - .env
    network_mode: host

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    network_mode: host

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@localhost:27017/
    network_mode: host
